pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label=ready-to-merge
      - check-success=build_and_test
    actions:
      merge:
        method: squash
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build_and_test
    actions:
      merge:
        method: squash
