name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16, 18, 20]
    name: Build and test (Node.js ${{ matrix.node }})

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:check

      - name: Format
        run: npm run format:check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
